name: Docker

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

permissions: write-all

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download npm artifacts
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Download composer artifacts
        uses: actions/download-artifact@v4
        with:
          name: composer
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Download public artifacts
        uses: actions/download-artifact@v4
        with:
          name: public
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Unpack artifacts
        run: |
          tar xvfz node_modules.tgz
          tar xvfz public.tgz
          tar xvfz composer.tgz

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PHP
        uses: docker/build-push-action@v4
        with:
          push: true
          target: php
          tags: blaj/dream-wedding-php-fpm:latest

      - name: Build and push Nginx
        uses: docker/build-push-action@v4
        with:
          push: true
          target: nginx
          tags: blaj/dream-wedding-nginx:latest
