name: Build

on:
  push:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

#        PHP
      - name: Setup PHP with Composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
          tools: composer:v2

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

#        Node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Yarn build
        run: yarn build

      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn

#        Tests
      - name: Create Database
        run: |
          PGPASSWORD=db psql -U db -h localhost -a -f ci-database-init.sql

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit

      - name: Run PHPStan analyse
        run: vendor/bin/phpstan analyse --memory-limit 2G -c ./phpstan/phpstan.neon

#        Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PHP
        uses: docker/build-push-action@v4
        with:
          push: true
          target: php
          build-args: |
            UID=${{ vars.UID }}
            GID=${{ vars.GID }}
          tags: blaj/dream-wedding-php-fpm:latest

      - name: Build and push Nginx
        uses: docker/build-push-action@v4
        with:
          push: true
          target: nginx
          build-args: |
            UID=${{ vars.UID }}
            GID=${{ vars.GID }}
          tags: blaj/dream-wedding-nginx:latest
